inhibit_all_warnings!

pod 'GPUImage'
pod 'Facebook-iOS-SDK'
pod 'TestFlightSDK', '~> 3.0'
pod 'BlocksKit'
pod 'CrittercismSDK'
pod 'Parse'
pod 'AFNetworking'
pod 'DAKeyboardControl'
pod 'AMAttributedHighlightLabel', '~> 0.0.1'